/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kt.giga.home.infra.domain.event;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CollectEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CollectEvent\",\"namespace\":\"com.kt.iot.core.integration.avro\",\"fields\":[{\"name\":\"svcTgtSeq\",\"type\":\"long\"},{\"name\":\"spotDevSeq\",\"type\":\"long\"},{\"name\":\"deviceModelId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"occDt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"attributes\",\"type\":{\"type\":\"map\",\"values\":[\"int\",\"long\",\"float\",\"double\",{\"type\":\"string\",\"avro.java.string\":\"String\"},\"boolean\"],\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long svcTgtSeq;
  @Deprecated public long spotDevSeq;
  @Deprecated public java.lang.String deviceModelId;
  @Deprecated public java.lang.String occDt;
  @Deprecated public java.util.Map<java.lang.String,java.lang.Object> attributes;
  @Deprecated public java.lang.String type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CollectEvent() {}

  /**
   * All-args constructor.
   */
  public CollectEvent(java.lang.Long svcTgtSeq, java.lang.Long spotDevSeq, java.lang.String deviceModelId, java.lang.String occDt, java.util.Map<java.lang.String,java.lang.Object> attributes, java.lang.String type) {
    this.svcTgtSeq = svcTgtSeq;
    this.spotDevSeq = spotDevSeq;
    this.deviceModelId = deviceModelId;
    this.occDt = occDt;
    this.attributes = attributes;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return svcTgtSeq;
    case 1: return spotDevSeq;
    case 2: return deviceModelId;
    case 3: return occDt;
    case 4: return attributes;
    case 5: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: svcTgtSeq = (java.lang.Long)value$; break;
    case 1: spotDevSeq = (java.lang.Long)value$; break;
    case 2: deviceModelId = (java.lang.String)value$; break;
    case 3: occDt = (java.lang.String)value$; break;
    case 4: attributes = (java.util.Map<java.lang.String,java.lang.Object>)value$; break;
    case 5: type = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'svcTgtSeq' field.
   */
  public java.lang.Long getSvcTgtSeq() {
    return svcTgtSeq;
  }

  /**
   * Sets the value of the 'svcTgtSeq' field.
   * @param value the value to set.
   */
  public void setSvcTgtSeq(java.lang.Long value) {
    this.svcTgtSeq = value;
  }

  /**
   * Gets the value of the 'spotDevSeq' field.
   */
  public java.lang.Long getSpotDevSeq() {
    return spotDevSeq;
  }

  /**
   * Sets the value of the 'spotDevSeq' field.
   * @param value the value to set.
   */
  public void setSpotDevSeq(java.lang.Long value) {
    this.spotDevSeq = value;
  }

  /**
   * Gets the value of the 'deviceModelId' field.
   */
  public java.lang.String getDeviceModelId() {
    return deviceModelId;
  }

  /**
   * Sets the value of the 'deviceModelId' field.
   * @param value the value to set.
   */
  public void setDeviceModelId(java.lang.String value) {
    this.deviceModelId = value;
  }

  /**
   * Gets the value of the 'occDt' field.
   */
  public java.lang.String getOccDt() {
    return occDt;
  }

  /**
   * Sets the value of the 'occDt' field.
   * @param value the value to set.
   */
  public void setOccDt(java.lang.String value) {
    this.occDt = value;
  }

  /**
   * Gets the value of the 'attributes' field.
   */
  public java.util.Map<java.lang.String,java.lang.Object> getAttributes() {
    return attributes;
  }

  /**
   * Sets the value of the 'attributes' field.
   * @param value the value to set.
   */
  public void setAttributes(java.util.Map<java.lang.String,java.lang.Object> value) {
    this.attributes = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /** Creates a new CollectEvent RecordBuilder */
  public static CollectEvent.Builder newBuilder() {
    return new CollectEvent.Builder();
  }
  
  /** Creates a new CollectEvent RecordBuilder by copying an existing Builder */
  public static CollectEvent.Builder newBuilder(CollectEvent.Builder other) {
    return new CollectEvent.Builder(other);
  }
  
  /** Creates a new CollectEvent RecordBuilder by copying an existing CollectEvent instance */
  public static CollectEvent.Builder newBuilder(CollectEvent other) {
    return new CollectEvent.Builder(other);
  }
  
  /**
   * RecordBuilder for CollectEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CollectEvent>
    implements org.apache.avro.data.RecordBuilder<CollectEvent> {

    private long svcTgtSeq;
    private long spotDevSeq;
    private java.lang.String deviceModelId;
    private java.lang.String occDt;
    private java.util.Map<java.lang.String,java.lang.Object> attributes;
    private java.lang.String type;

    /** Creates a new Builder */
    private Builder() {
      super(CollectEvent.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(CollectEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.svcTgtSeq)) {
        this.svcTgtSeq = data().deepCopy(fields()[0].schema(), other.svcTgtSeq);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.spotDevSeq)) {
        this.spotDevSeq = data().deepCopy(fields()[1].schema(), other.spotDevSeq);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.deviceModelId)) {
        this.deviceModelId = data().deepCopy(fields()[2].schema(), other.deviceModelId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.occDt)) {
        this.occDt = data().deepCopy(fields()[3].schema(), other.occDt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.attributes)) {
        this.attributes = data().deepCopy(fields()[4].schema(), other.attributes);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.type)) {
        this.type = data().deepCopy(fields()[5].schema(), other.type);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CollectEvent instance */
    private Builder(CollectEvent other) {
            super(CollectEvent.SCHEMA$);
      if (isValidValue(fields()[0], other.svcTgtSeq)) {
        this.svcTgtSeq = data().deepCopy(fields()[0].schema(), other.svcTgtSeq);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.spotDevSeq)) {
        this.spotDevSeq = data().deepCopy(fields()[1].schema(), other.spotDevSeq);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.deviceModelId)) {
        this.deviceModelId = data().deepCopy(fields()[2].schema(), other.deviceModelId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.occDt)) {
        this.occDt = data().deepCopy(fields()[3].schema(), other.occDt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.attributes)) {
        this.attributes = data().deepCopy(fields()[4].schema(), other.attributes);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.type)) {
        this.type = data().deepCopy(fields()[5].schema(), other.type);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'svcTgtSeq' field */
    public java.lang.Long getSvcTgtSeq() {
      return svcTgtSeq;
    }
    
    /** Sets the value of the 'svcTgtSeq' field */
    public CollectEvent.Builder setSvcTgtSeq(long value) {
      validate(fields()[0], value);
      this.svcTgtSeq = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'svcTgtSeq' field has been set */
    public boolean hasSvcTgtSeq() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'svcTgtSeq' field */
    public CollectEvent.Builder clearSvcTgtSeq() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'spotDevSeq' field */
    public java.lang.Long getSpotDevSeq() {
      return spotDevSeq;
    }
    
    /** Sets the value of the 'spotDevSeq' field */
    public CollectEvent.Builder setSpotDevSeq(long value) {
      validate(fields()[1], value);
      this.spotDevSeq = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'spotDevSeq' field has been set */
    public boolean hasSpotDevSeq() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'spotDevSeq' field */
    public CollectEvent.Builder clearSpotDevSeq() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'deviceModelId' field */
    public java.lang.String getDeviceModelId() {
      return deviceModelId;
    }
    
    /** Sets the value of the 'deviceModelId' field */
    public CollectEvent.Builder setDeviceModelId(java.lang.String value) {
      validate(fields()[2], value);
      this.deviceModelId = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'deviceModelId' field has been set */
    public boolean hasDeviceModelId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'deviceModelId' field */
    public CollectEvent.Builder clearDeviceModelId() {
      deviceModelId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'occDt' field */
    public java.lang.String getOccDt() {
      return occDt;
    }
    
    /** Sets the value of the 'occDt' field */
    public CollectEvent.Builder setOccDt(java.lang.String value) {
      validate(fields()[3], value);
      this.occDt = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'occDt' field has been set */
    public boolean hasOccDt() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'occDt' field */
    public CollectEvent.Builder clearOccDt() {
      occDt = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'attributes' field */
    public java.util.Map<java.lang.String,java.lang.Object> getAttributes() {
      return attributes;
    }
    
    /** Sets the value of the 'attributes' field */
    public CollectEvent.Builder setAttributes(java.util.Map<java.lang.String,java.lang.Object> value) {
      validate(fields()[4], value);
      this.attributes = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'attributes' field has been set */
    public boolean hasAttributes() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'attributes' field */
    public CollectEvent.Builder clearAttributes() {
      attributes = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public java.lang.String getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public CollectEvent.Builder setType(java.lang.String value) {
      validate(fields()[5], value);
      this.type = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'type' field */
    public CollectEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public CollectEvent build() {
      try {
        CollectEvent record = new CollectEvent();
        record.svcTgtSeq = fieldSetFlags()[0] ? this.svcTgtSeq : (java.lang.Long) defaultValue(fields()[0]);
        record.spotDevSeq = fieldSetFlags()[1] ? this.spotDevSeq : (java.lang.Long) defaultValue(fields()[1]);
        record.deviceModelId = fieldSetFlags()[2] ? this.deviceModelId : (java.lang.String) defaultValue(fields()[2]);
        record.occDt = fieldSetFlags()[3] ? this.occDt : (java.lang.String) defaultValue(fields()[3]);
        record.attributes = fieldSetFlags()[4] ? this.attributes : (java.util.Map<java.lang.String,java.lang.Object>) defaultValue(fields()[4]);
        record.type = fieldSetFlags()[5] ? this.type : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
