--1. HOM_MANAGER_PROVISION_SUBS_TXN

CREATE TABLE HOM_MANAGER_PROVISION_SUBS_TXN
(
	SVC_CONT_ID          VARCHAR(11) NOT NULL ,
	SUBS_IF_HST_SEQ      NUMERIC(10) NOT NULL ,
	CUST_ID              VARCHAR(11) NULL ,
	CUST_NM              VARCHAR(100) NULL ,
	SVC_NO               VARCHAR(12) NULL ,
	SVC_TRT_CD           VARCHAR(4) NULL ,
	PROD_CD              VARCHAR(4) NULL ,
	PROD_DTL_CD          VARCHAR(4) NULL ,
	ODER_NO              VARCHAR(11) NULL ,
	SUBS_APY_DT          TIMESTAMP NULL ,
	HOM_GW_MODEL_NM      VARCHAR(70) NULL ,
	HOM_GW_MODEL_CD      VARCHAR(10) NULL ,
	HOM_GW_SVC_CONT_ID   VARCHAR(11) NULL ,
	HOM_GW_MAC_ADR       VARCHAR(30) NULL ,
	HOM_GW_SERIAL_NO     VARCHAR(30) NULL ,
	SRVR_TRT_TYPE_CD     VARCHAR(4) NULL ,
	IDMS_ODER_INPUT_DT   TIMESTAMP NULL ,
	DATA_IF_DIV_CD       VARCHAR(1) NULL ,
	ROLLBK_BEF_STTUS_CD  VARCHAR(4) NULL ,
	SUBS_IF_INFO_CRET_DT TIMESTAMP NULL ,
	SUBS_IF_CMPLT_DT     TIMESTAMP NULL ,
	SUBS_IF_CMPLT_YN     VARCHAR(1) NULL
);


COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SVC_CONT_ID IS '프로비저닝청약내역 서비스계약아이디'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SVC_TRT_CD IS '프로비저닝청약내역 서비스처리코드'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.PROD_CD IS '프로비저닝청약내역 상품코드'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.ODER_NO IS '프로비저닝청약내역 오더번호'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SUBS_APY_DT IS '프로비저닝청약내역 청약신청일시'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.CUST_ID IS '프로비저닝청약내역 고객아이디'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.CUST_NM IS '프로비저닝청약내역 고객이름'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.HOM_GW_SVC_CONT_ID IS '프로비저닝청약내역 홈CCTV서비스계약아이디'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.HOM_GW_MAC_ADR IS '프로비저닝청약내역 홈CCTVMAC주소'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SRVR_TRT_TYPE_CD IS '프로비저닝청약내역 서비스처리유형코드'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.IDMS_ODER_INPUT_DT IS '프로비저닝청약내역 IDMS오더입력시간'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SUBS_IF_CMPLT_YN IS '프로비저닝청약내역 청약연동완료여부'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.PROD_DTL_CD IS '프로비저닝청약내역 상품상세코드'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.HOM_GW_MODEL_NM IS '프로비저닝청약내역 홈CCTV모델명'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.HOM_GW_MODEL_CD IS '프로비저닝청약내역 홈CCTV모델코드'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.DATA_IF_DIV_CD IS '프로비저닝청약내역 데이터연동구분코드'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.ROLLBK_BEF_STTUS_CD IS '프로비저닝청약내역 롤백이전상태코드'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SUBS_IF_HST_SEQ IS '프로비저닝청약내역 청약연동이력일련번호'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SUBS_IF_INFO_CRET_DT IS '프로비저닝청약내역 쳥약연동정보생성일시'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SUBS_IF_CMPLT_DT IS '프로비저닝청약내역 청약연동완료일시'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.SVC_NO IS '프로비저닝청약내역 서비스번호'
;

COMMENT ON COLUMN HOM_MANAGER_PROVISION_SUBS_TXN.HOM_GW_SERIAL_NO IS '프로비저닝청약내역 홈CCTV시리얼번호'
;

ALTER TABLE HOM_MANAGER_PROVISION_SUBS_TXN
	ADD CONSTRAINT  HOM_MANAGER_PROVISION_SUBS_TXN_PK PRIMARY KEY (SVC_CONT_ID,SUBS_IF_HST_SEQ)
;



--2. EGNCY_CNTC_NET_TXN
CREATE TABLE EGNCY_CNTC_NET_TXN
(
	EGNCY_CNTC_NET_SEQ   NUMERIC(19) NOT NULL ,
	SVC_TGT_SEQ          NUMERIC(10) NOT NULL ,
	NM                   VARCHAR(10) NULL ,
	TEL_NO               VARCHAR(20) NULL ,
	CRET_DT              TIMESTAMP NULL ,
	AMD_DT               TIMESTAMP NULL ,
        NTC_RCV_YN           VARCHAR(1)
)
;

COMMENT ON COLUMN EGNCY_CNTC_NET_TXN.EGNCY_CNTC_NET_SEQ IS '비상연락망내역 비상연락망일련번호'
;

COMMENT ON COLUMN EGNCY_CNTC_NET_TXN.SVC_TGT_SEQ IS '비상연락망내역 서비스대상일련번호'
;

COMMENT ON COLUMN EGNCY_CNTC_NET_TXN.NM IS '비상연락망내역 이름'
;

COMMENT ON COLUMN EGNCY_CNTC_NET_TXN.TEL_NO IS '비상연락망내역 전화번호'
;

COMMENT ON COLUMN EGNCY_CNTC_NET_TXN.CRET_DT IS '비상연락망내역 생성일시'
;

COMMENT ON COLUMN EGNCY_CNTC_NET_TXN.AMD_DT IS '비상연락망내역 수정일시'
;

COMMENT ON COLUMN EGNCY_CNTC_NET_TXN.NTC_RCV_YN IS '비상연락망내역 알림수신여부'
;

ALTER TABLE EGNCY_CNTC_NET_TXN
	ADD CONSTRAINT  EGNCY_CNTC_NET_TXN_PK PRIMARY KEY (EGNCY_CNTC_NET_SEQ,SVC_TGT_SEQ)
;

--
ALTER TABLE EGNCY_CNTC_NET_TXN
	ADD CONSTRAINT EGNCY_CNTC_NET_TXN_FK01 FOREIGN KEY (SVC_TGT_SEQ) REFERENCES SVC_TGT_BAS (SVC_TGT_SEQ)
;


--3. MBR_PWD_TXN
CREATE TABLE MBR_PWD_TXN
(
	TRGT_MBR_SEQ         NUMERIC(10) NOT NULL ,
	SPOT_DEV_SEQ         NUMERIC(19) NOT NULL ,
	TRGT_NM              VARCHAR(10) NULL ,
	PWD                  VARCHAR(20) NULL ,
	SVC_TGT_SEQ          NUMERIC(10) NOT NULL ,
        USER_CD_SEQ          NUMERIC(2)
)
;

COMMENT ON COLUMN MBR_PWD_TXN.TRGT_MBR_SEQ IS '회원비밀번호내역 대상자회원일련번호'
;

COMMENT ON COLUMN MBR_PWD_TXN.SPOT_DEV_SEQ IS '회원비밀번호내역 현장장치일련번호'
;

COMMENT ON COLUMN MBR_PWD_TXN.TRGT_NM IS '회원비밀번호내역 대상자이름'
;

COMMENT ON COLUMN MBR_PWD_TXN.PWD IS '회원비밀번호내역 비밀번호'
;

COMMENT ON COLUMN MBR_PWD_TXN.SVC_TGT_SEQ IS '회원비밀번호내역 서비스대상일련번호'
;

COMMENT ON COLUMN MBR_PWD_TXN.SVC_TGT_SEQ IS '회원비밀번호내역 유저코드일련번호'
;

ALTER TABLE MBR_PWD_TXN
	ADD CONSTRAINT  MBR_PWD_TXN_PK PRIMARY KEY (SVC_TGT_SEQ,TRGT_MBR_SEQ,SPOT_DEV_SEQ)
;

--
ALTER TABLE MBR_PWD_TXN
	ADD CONSTRAINT MBR_PWD_TXN_FK01 FOREIGN KEY (SVC_TGT_SEQ) REFERENCES SVC_TGT_BAS (SVC_TGT_SEQ)
;


--4. FILE_ADM_TXN

CREATE TABLE FILE_ADM_TXN
(
       FILE_SEQ         NUMERIC(20) ,
       ORIGIN_FILE_NM   VARCHAR(200) ,
       STORE_FILE_NM    VARCHAR(200) ,
       FILE_SIZE_VAL    NUMERIC(10) ,
       ACES_URL_ADR     VARCHAR(250) ,
       CONTS_TYPE_VAL   VARCHAR(10) 
)
;


COMMENT ON COLUMN FILE_ADM_TXN.FILE_SEQ IS '파일관리내역 파일일련번호'
;

COMMENT ON COLUMN FILE_ADM_TXN.ORIGIN_FILE_NM IS '파일관리내역 원본파일명'
;

COMMENT ON COLUMN FILE_ADM_TXN.STORE_FILE_NM IS '파일관리내역 저장파일명'
;

COMMENT ON COLUMN FILE_ADM_TXN.FILE_SIZE_VAL IS '파일관리내역 파일사이즈값'
;

COMMENT ON COLUMN FILE_ADM_TXN.ACES_URL_ADR IS '파일관리내역 접근URL주소'
;

COMMENT ON COLUMN FILE_ADM_TXN.CONTS_TYPE_VAL IS '파일관리내역 컨텐츠타입값'
;

ALTER TABLE FILE_ADM_TXN
	ADD CONSTRAINT  FILE_ADM_TXN_PK PRIMARY KEY (FILE_SEQ)
;



--5. MANAGER_PROF_TXN
CREATE TABLE MANAGER_PROF_TXN
(
	MBR_SEQ              NUMERIC(10) NOT NULL ,
	MBR_NICK_NM          VARCHAR(10) NULL ,
        FILE_SEQ             NUMERIC(20)
)
;

COMMENT ON COLUMN MANAGER_PROF_TXN.MBR_SEQ IS '회원기본 회원일련번호'
;

COMMENT ON COLUMN MANAGER_PROF_TXN.MBR_NICK_NM IS '매니저프로파일내역 회원닉네임'
;

ALTER TABLE MANAGER_PROF_TXN
	ADD CONSTRAINT  MANAGER_PROF_TXN_PK PRIMARY KEY (MBR_SEQ)
;


ALTER TABLE MANAGER_PROF_TXN
	ADD CONSTRAINT MANAGER_PROF_TXN_FK01 FOREIGN KEY (MBR_SEQ) REFERENCES MBR_BAS (MBR_SEQ)
;

ALTER TABLE MANAGER_PROF_TXN
	ADD CONSTRAINT MANAGER_PROF_TXN_FK02 FOREIGN KEY (FILE_SEQ) REFERENCES FILE_ADM_TXN (FILE_SEQ)
;



--6. HOM_MODE_STTUS_UPD_TXN
CREATE TABLE HOM_MODE_STTUS_UPD_TXN
(
	SVC_TGT_SEQ          NUMERIC(10) NOT NULL ,
	HOM_MODE_CD          VARCHAR(3) NULL ,
	CRET_DT              TIMESTAMP NULL ,
	AMD_DT               TIMESTAMP NULL ,
	SETUP_MBR_SEQ        NUMERIC(10) NULL 
)
;

COMMENT ON COLUMN HOM_MODE_STTUS_UPD_TXN.SVC_TGT_SEQ IS '홈모드상태갱신내역 서비스대상일련번호'
;

COMMENT ON COLUMN HOM_MODE_STTUS_UPD_TXN.HOM_MODE_CD IS '홈모드상태갱신내역 서비스대상일련번호'
;

COMMENT ON COLUMN HOM_MODE_STTUS_UPD_TXN.CRET_DT IS '홈모드상태갱신내역 생성일시'
;

COMMENT ON COLUMN HOM_MODE_STTUS_UPD_TXN.AMD_DT IS '홈모드상태갱신내역 수정일시'
;

COMMENT ON COLUMN HOM_MODE_STTUS_UPD_TXN.SETUP_MBR_SEQ IS '홈모드상태갱신내역 설정회원일련번호'
;

ALTER TABLE HOM_MODE_STTUS_UPD_TXN
	ADD CONSTRAINT  HOM_MODE_STTUS_UPD_TXN_PK PRIMARY KEY (SVC_TGT_SEQ)
;

--
ALTER TABLE HOM_MODE_STTUS_UPD_TXN
	ADD CONSTRAINT HOM_MODE_STTUS_UPD_TXN_FK01 FOREIGN KEY (SVC_TGT_SEQ) REFERENCES SVC_TGT_BAS (SVC_TGT_SEQ)
;



--7. HOM_MODE_BY_STTUS_SETUP_TXN
CREATE TABLE HOM_MODE_BY_STTUS_SETUP_TXN
(
	MBR_SEQ              NUMERIC(10) NOT NULL ,
	UNIT_SVC_CD          VARCHAR(3) NOT NULL ,
	SVC_THEME_CD         VARCHAR(3) NOT NULL ,
	DSTR_CD              VARCHAR(3) NOT NULL ,
	SPOT_DEV_SEQ         NUMERIC(19) NOT NULL ,
	SVC_TGT_SEQ          NUMERIC(10) NOT NULL ,
	SETUP_STTUS_CD       VARCHAR(3) NULL ,
	CRET_DT              TIMESTAMP NULL ,
	AMD_DT               TIMESTAMP NULL ,
	HOM_MODE_CD          VARCHAR(10) NOT NULL 
)
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.MBR_SEQ IS '홈모드별상태설정내역 회원일련번호'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.UNIT_SVC_CD IS '홈모드별상태설정내역 단위서비스코드'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.SVC_THEME_CD IS '홈모드별상태설정내역 서비스테마코드'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.DSTR_CD IS '홈모드별상태설정내역 지역코드'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.SPOT_DEV_SEQ IS '홈모드별상태설정내역 현장장치일련번호'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.SVC_TGT_SEQ IS '홈모드별상태설정내역 서비스대상일련번호'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.SETUP_STTUS_CD IS '홈모드별상태설정내역 설정상태코드'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.CRET_DT IS '홈모드별상태설정내역 생성일시'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.AMD_DT IS '홈모드별상태설정내역 수정일시'
;

COMMENT ON COLUMN HOM_MODE_BY_STTUS_SETUP_TXN.HOM_MODE_CD IS '홈모드별상태설정내역 홈모드코드'
;

ALTER TABLE HOM_MODE_BY_STTUS_SETUP_TXN
	ADD CONSTRAINT  HOM_MODE_BY_STTUS_SETUP_TXN_PK PRIMARY KEY (MBR_SEQ,DSTR_CD,SVC_THEME_CD,UNIT_SVC_CD,SPOT_DEV_SEQ,SVC_TGT_SEQ,HOM_MODE_CD)
;

--
ALTER TABLE HOM_MODE_BY_STTUS_SETUP_TXN
	ADD CONSTRAINT HOM_MODE_BY_STTUS_SETUP_TXN_FK01 FOREIGN KEY (MBR_SEQ, DSTR_CD, SVC_THEME_CD, UNIT_SVC_CD) REFERENCES SVC_MBR_REL (MBR_SEQ, DSTR_CD, SVC_THEME_CD, UNIT_SVC_CD)
;


ALTER TABLE HOM_MODE_BY_STTUS_SETUP_TXN
	ADD CONSTRAINT HOM_MODE_BY_STTUS_SETUP_TXN_FK02 FOREIGN KEY (SPOT_DEV_SEQ, SVC_TGT_SEQ) REFERENCES SPOT_DEV_BAS (SPOT_DEV_SEQ, SVC_TGT_SEQ)
;


--8. spot_dev_bas
ALTER TABLE spot_dev_bas
   ADD COLUMN "up_spot_dev_seq" numeric(19,0);
COMMENT ON COLUMN spot_dev_bas."up_spot_dev_seq"
  IS '현장장치기본 상위장치일련번호';

ALTER TABLE spot_dev_bas
   ADD COLUMN "up_svc_tgt_seq" numeric(10,0);
COMMENT ON COLUMN spot_dev_bas."up_svc_tgt_seq"
  IS '현장장치기본 상위서비스대상일련번호';


--9. svc_ets_rel
DROP TABLE svc_ets_rel;

CREATE TABLE SVC_ETS_REL
(
	ETS_MBR_SEQ          NUMERIC(10) NOT NULL ,
	MBR_SEQ              NUMERIC(10) NOT NULL ,
	DSTR_CD              VARCHAR(3) NOT NULL ,
	SVC_THEME_CD         VARCHAR(3) NOT NULL ,
	UNIT_SVC_CD          VARCHAR(3) NOT NULL ,
	CRET_DT              TIMESTAMP NULL ,
	AMD_DT               TIMESTAMP NULL ,
	SVC_TGT_SEQ          NUMERIC(10) NOT NULL 
)
;

COMMENT ON COLUMN SVC_ETS_REL.ETS_MBR_SEQ IS '서비스위임관계 위임회원일련번호'
;

COMMENT ON COLUMN SVC_ETS_REL.MBR_SEQ IS '회원기본 회원일련번호'
;

COMMENT ON COLUMN SVC_ETS_REL.DSTR_CD IS '단위서비스 지역코드'
;

COMMENT ON COLUMN SVC_ETS_REL.SVC_THEME_CD IS '단위서비스 서비스테마코드'
;

COMMENT ON COLUMN SVC_ETS_REL.UNIT_SVC_CD IS '단위서비스 단위서비스코드'
;

COMMENT ON COLUMN SVC_ETS_REL.CRET_DT IS '서비스위임관계 생성일시'
;

COMMENT ON COLUMN SVC_ETS_REL.AMD_DT IS '서비스위임관계 수정일시'
;

COMMENT ON COLUMN SVC_ETS_REL.SVC_TGT_SEQ IS '서비스위임관계 서비스대상일련번호'
;

ALTER TABLE SVC_ETS_REL
	ADD CONSTRAINT  SVC_ETS_REL_PK PRIMARY KEY (ETS_MBR_SEQ,MBR_SEQ,DSTR_CD,SVC_THEME_CD,UNIT_SVC_CD,SVC_TGT_SEQ)
;
ALTER TABLE SVC_ETS_REL
	ADD CONSTRAINT SVC_ETS_REL_FK01 FOREIGN KEY (MBR_SEQ, DSTR_CD, SVC_THEME_CD, UNIT_SVC_CD) REFERENCES SVC_MBR_REL (MBR_SEQ, DSTR_CD, SVC_THEME_CD, UNIT_SVC_CD)
;

--10. MBR_SPOT_DEV_SETUP_TXN
CREATE TABLE MBR_SPOT_DEV_SETUP_TXN
(
	MBR_SEQ              NUMERIC(10) NOT NULL ,
	DSTR_CD              VARCHAR(3) NOT NULL ,
	SVC_THEME_CD         VARCHAR(3) NOT NULL ,
	UNIT_SVC_CD          VARCHAR(3) NOT NULL ,
        SVC_TGT_SEQ          NUMERIC(10) NOT NULL,
        SPOT_DEV_SEQ	     NUMERIC(19) NOT NULL,
	GROUP_SETUP_CD       VARCHAR(10) NOT NULL ,
	SETUP_CD             VARCHAR(10) NOT NULL ,

	SETUP_VAL            VARCHAR(50) NULL ,
CONSTRAINT  MBR_SPOT_DEV_SETUP_TXN_PK PRIMARY KEY (MBR_SEQ, DSTR_CD, SVC_THEME_CD, UNIT_SVC_CD, SVC_TGT_SEQ, SPOT_DEV_SEQ, GROUP_SETUP_CD, SETUP_CD)
)
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.MBR_SEQ IS '회원현장장치설정내역 회원일련번호'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.DSTR_CD IS '회원현장장치설정내역 지역코드'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.SVC_THEME_CD IS '회원현장장치설정내역 서비스테마코드'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.UNIT_SVC_CD IS '회원현장장치설정내역 단위서비스코드'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.SVC_TGT_SEQ IS '회원현장장치설정내역 서비스대상일련번호'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.SPOT_DEV_SEQ IS '회원현장장치설정내역 현장장치일련번호'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.GROUP_SETUP_CD IS '회원현장장치설정내역 그룹설정코드'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.SETUP_CD IS '회원현장장치설정내역 설정코드'
;

COMMENT ON COLUMN MBR_SPOT_DEV_SETUP_TXN.SETUP_VAL IS '회원현장장치설정내역 설정값'
;

ALTER TABLE MBR_SPOT_DEV_SETUP_TXN
	ADD CONSTRAINT MBR_SPOT_DEV_SETUP_TXN_FK01 FOREIGN KEY (MBR_SEQ, DSTR_CD, SVC_THEME_CD, UNIT_SVC_CD) REFERENCES SVC_MBR_REL (MBR_SEQ, DSTR_CD, SVC_THEME_CD, UNIT_SVC_CD)
;

ALTER TABLE MBR_SPOT_DEV_SETUP_TXN
	ADD CONSTRAINT MBR_SPOT_DEV_SETUP_TXN_FK02 FOREIGN KEY (SPOT_DEV_SEQ, SVC_TGT_SEQ) REFERENCES SPOT_DEV_BAS (SPOT_DEV_SEQ, SVC_TGT_SEQ)
;